#!/usr/bin/env bash
# Register a desktop handler for the app:// OAuth redirect.
#
# Why this exists: the OAuth client is a mobile app, and its registered
# redirect is a custom scheme. If the vendor's own app is installed, the OS
# hands the redirect to it and that app redeems the single-use authorization
# code -- so by the time you try to use it, it is already spent and the token
# exchange fails with invalid_grant. Claiming the scheme first means the code
# comes to you instead.
#
# Usage:
#   ./install-redirect-handler.sh https://vigilo.example.com
#
# Linux/XDG only. On other desktops, capture the redirect from the browser's
# devtools network log instead (see the README).

set -e

UI_URL="${1:-}"
if [[ -z $UI_URL ]]; then
  echo "Usage: $0 <re-auth UI base URL>" >&2
  exit 1
fi
UI_URL="${UI_URL%/}"

HANDLER="$HOME/.local/bin/vigilo-uri-handler"
DESKTOP_FILE="$HOME/.local/share/applications/vigilo-uri-handler.desktop"

mkdir -p "$(dirname "$HANDLER")" "$(dirname "$DESKTOP_FILE")"

cat >"$HANDLER" <<EOF
#!/usr/bin/env bash
# Receives the app:// redirect from the desktop and gets the code to the
# re-auth UI. Generated by install-redirect-handler.sh -- edit that instead.
set -e

UI_URL="$UI_URL"
EOF

cat >>"$HANDLER" <<'EOF'
notify() {
  command -v notify-send >/dev/null 2>&1 || return 0
  notify-send "Vigilo" "$1" || true
}

url="${1:-}"
[[ -z $url ]] && exit 0
query="${url#*\?}"

# Best path: hand it to the browser, which already holds a session for the UI.
# The page pre-fills the code and waits for a click; it does not auto-submit.
if [[ -n $query && $query != "$url" ]] && command -v xdg-open >/dev/null 2>&1; then
  xdg-open "${UI_URL}/paste?${query}" >/dev/null 2>&1 && exit 0
fi

# Fallbacks, in case there is no browser to hand it to.
for clip in wl-copy xclip pbcopy; do
  if command -v "$clip" >/dev/null 2>&1; then
    case $clip in
      xclip) printf '%s' "$url" | xclip -selection clipboard ;;
      *) printf '%s' "$url" | "$clip" ;;
    esac
    # Notifications are cosmetic and fail on a headless session; under set -e
    # that would exit non-zero after the code has already been captured.
    notify "Auth code copied to clipboard"
    exit 0
  fi
done

printf '%s\n' "$url" >/tmp/vigilo_code
notify "Auth code written to /tmp/vigilo_code"
echo "Captured: $url"
EOF

chmod +x "$HANDLER"

cat >"$DESKTOP_FILE" <<EOF
[Desktop Entry]
Name=Vigilo URI Handler
Exec=$HANDLER %u
Type=Application
NoDisplay=true
MimeType=x-scheme-handler/app;
EOF

xdg-mime default vigilo-uri-handler.desktop x-scheme-handler/app
update-desktop-database "$(dirname "$DESKTOP_FILE")" 2>/dev/null || true

echo "Handler registered for x-scheme-handler/app"
echo "  handler: $HANDLER"
echo "  ui:      $UI_URL"
echo
echo "Re-authenticating from now on: open $UI_URL, click 'Log in to Vigilo',"
echo "complete the login, and the browser will land back on the form with the"
echo "code filled in. Click 'Save tokens'."
echo
echo "Note this claims app:// for the whole desktop. If the vendor's own"
echo "application is installed and you want it back, run:"
echo "  xdg-mime default <their>.desktop x-scheme-handler/app"
